DROP TABLE PRODUCT;

SELECT * FROM PRODUCT;

CREATE TABLE PRODUCT(
    ITEMNO NUMBER PRIMARY KEY, -- 번호
    PRODUCTNAME VARCHAR2(30) NOT NULL UNIQUE, -- 상품이름
    PRODUCTNO VARCHAR2(15) NOT NULL, -- 상품코드
    PRODUCTCLASS CHAR(1) CHECK(GENDER IN ('A', 'B', 'C')), -- 상품종류
    COLOR CHAR(2) CHECK(GENDER IN ('R', 'BK', 'B', 'SV', 'GD', 'GR', 'W')), -- 상품색상
    ODQUENTITY NUMBER,-- 발주수량
    STOCK NUMBER, -- 재고수량
    INCOMEPRICE NUMBER NOT NULL, -- 개당 발주가격
    INCOMEDATE DATE DEFAULT SYSDATE NOT NULL, -- 도착일
    ADDRESS VARCHAR2(4) --상품위치
);

SELECT * FROM PRODUCT;

DROP SEQUENCE SEQ_ITEMNO;
CREATE SEQUENCE SEQ_ITEMNO
NOCACHE;

INSERT INTO PRODUCT
VALUES(SEQ_ITEMNO.NEXTVAL, 'A9M3', 'ILCE-A9M3', 'A', null, 20, 10, 6500000, '2024-02-01', 'P1' );

INSERT INTO PRODUCT
VALUES(SEQ_ITEMNO.NEXTVAL, 'ZHIYUN MOLUS X100', 'ZMX100', 'B', null, 50, 10, 150000, '2024-01-15', 'P2' );

INSERT INTO PRODUCT
VALUES(SEQ_ITEMNO.NEXTVAL, '메모리카드케이스', 'PC-20', 'C', 'R', 300, 50, 1500, '2024-02-05', 'P11' );

COMMIT;
