DROP TABLE MEMBER;
DROP TABLE MOVIE;

CREATE TABLE MEMBER(
    USERNO	NUMBER PRIMARY KEY, --번호
    USERID	VARCHAR2(15 BYTE) NOT NULL UNIQUE, --아이디
    USERPWD	VARCHAR2(15 BYTE) NOT NULL, -- 비밀번호
    USERNAME VARCHAR2(20 BYTE) NOT NULL, --이름
    PHONE	CHAR(11 BYTE), --전화번호
    ENROLLDATE	DATE DEFAULT SYSDATE NOT NULL --가입일
);

CREATE TABLE MOVIE(
    MOVIENO	NUMBER PRIMARY KEY, --번호
    TITLE	VARCHAR2(50 BYTE) NOT NULL, -- 제목
    GENRE	VARCHAR2(30 BYTE) NOT NULL -- 장르
);

DROP SEQUENCE SEQ_USERNO;
DROP SEQUENCE SEQ_MOVIENO;

CREATE SEQUENCE SEQ_USERNO
NOCYCLE
NOCACHE;

INSERT INTO MEMBER
VALUES(SEQ_USERNO.NEXTVAL, 'admin', '123', '관리자', null, sysdate);

COMMIT;


CREATE SEQUENCE SEQ_MOVIENO
NOCYCLE
NOCACHE;

INSERT INTO MOVIE
VALUES(SEQ_MOVIENO.NEXTVAL, '범죄마을3', '범죄, 액션');

INSERT INTO MOVIE
VALUES(SEQ_MOVIENO.NEXTVAL, '파봐', '미스터리, 스릴러');

INSERT INTO MOVIE
VALUES(SEQ_MOVIENO.NEXTVAL, '웡가', '어린이, 판타지');

INSERT INTO MOVIE
VALUES(SEQ_MOVIENO.NEXTVAL, '스즈메가 문잠금', '모험, 드라마');

COMMIT;